name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACTIONS_CONTAINER_REGISTRY_PAT }}

      - name: "Build the pgsnap image"
        run: |
          docker build . --build-arg RELEASE=${{ github.ref_name }} --tag ghcr.io/openformation/pgsnap:${{ github.ref_name }}
          docker push ghcr.io/openformation/pgsnap:${{ github.ref_name }}
